version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    links:
      - backend
    volumes:
      - ./docs:/app/build


  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - backend
